name: URLify-Pipeline

on:
    push:
        branches:
            - master

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v2
            - name: Login to Docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t divyarajsinh/URLify:latest .
            - name: Push Docker Image
              run: docker push divyarajsinh/URLify:latest
    
    deploy:
        needs: build
        runs-on: [aws-EC2]
        steps:
            - name: Pull the image from docker hub
              run: docker pull divyarajsinh/URLify:latest
            - name: Stop the existing container
              run: docker stop URLify || true
            - name: Remove the existing container
              run: docker rm -f URLify || true
            - name: Run Docker container
              run: docker run -d --name URLify -p 3000:3000 divyarajsinh/URLify:latest
